### ISSUE TITLE
mangopay-android-vault-sdk not found

### ISSUE THREAD

**Issue by PatelJa02** [Mangopay/mangopay-ios-vault-sdk#7]
Hello Mangopay iOS Team,

Could you please check with the android team for the **mangopay-android-vault-sdk github repository** as I am not getting the same on github. I need to report some SDK related issues over there.

I know it is not related to this "[mangopay-ios-vault-sdk]" repository, but could you please help?

**Comment by jidefela-mgp** [comment]
Hi @PatelJa02 , 

Our Android SDK is not available on Github at the moment. Please refer to [our documentation](https://mangopay.com/docs/sdk/vault-android) for instructions for how to access and integrate the Android SDK. 

If you run into any problems while following these steps, please open an issue in our  [Android example repository]( https://github.com/Mangopay/mangopay-android-sdk-examples) so we can address it.

**Comment by PatelJa02** [comment]
Thanks you so much @jidefela-mgp I will post issue there
